name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get ruff version from requirements file
        id: version
        run: |
          VERSION=$(grep -m 1 -oP 'ruff==\K(.*)' requirements.txt)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # - uses: chartboost/ruff-action@v1
      #   with:
      #     version: ${{ steps.version.outputs.version }}
      #     args: check --no-fix

      - uses: chartboost/ruff-action@v1
        with:
          version: ${{ steps.version.outputs.version }}
          args: format --diff
